# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# gem "github-pages", group: :jekyll_plugins

# title: [Welcome to Hajun's blog]
# description: [this is my blog]

# _config.yml

remote_theme: "jekyll/minima@1e8a445"
